name: Build AmneziaWG for WR1043ND

on:
  workflow_dispatch:   # Ручной запуск
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: "Build for ath79/generic"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: v22.03.3
          fetch-depth: 0

      - name: Setup feeds
        run: |
          echo "src-git awgopenwrt https://github.com/yury-sannikov/awg-openwrt.git" >> feeds.conf
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure
        run: |
          wget https://downloads.openwrt.org/releases/22.03.3/targets/ath79/generic/config.buildinfo -O .config
          echo "CONFIG_PACKAGE_kmod-amneziawg=m" >> .config
          echo "CONFIG_PACKAGE_amneziawg-tools=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-amneziawg=y" >> .config
          make defconfig

      - name: Build packages
        run: |
          make package/amneziawg-tools/compile -j$(nproc) V=s || true
          make package/luci-app-amneziawg/compile -j$(nproc) V=s || true
          make package/kmod-amneziawg/compile -j$(nproc) V=s || true

      - name: Prepare artifacts
        run: |
          mkdir -p awgrelease
          cp bin/packages/mips_24kc/awgopenwrt/*.ipk awgrelease/ 2>/dev/null || true
          cp bin/targets/ath79/generic/packages/kmod-amneziawg*.ipk awgrelease/ 2>/dev/null || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: amneziawg-packages
          path: awgrelease/
